### ISSUE TITLE
CUDA error using set_diag for empty SparseTensor

### ISSUE THREAD

**Issue by yascho** [rusty1s/pytorch_sparse#164]
Hi, I have a problem with set_diag for an empty SparseTensor:

```
import scipy.sparse as sp
from torch_sparse import SparseTensor, set_diag
```

What I expect (works on CPU):
```
M = SparseTensor.from_scipy(sp.csr_matrix((2,2)))
set_diag(M)
---
SparseTensor(row=tensor([0, 1]),
             col=tensor([0, 1]),
             val=tensor([1., 1.], dtype=torch.float64),
             size=(2, 2), nnz=2, density=50.00%)
```

However, what I observe on GPU:

```
M = SparseTensor.from_scipy(sp.csr_matrix((2,2))).cuda()
set_diag(M)
---
RuntimeError: CUDA error: invalid configuration argument
```

Interestingly, I do not observe the issue for a non-empty SparseTensor. I am not sure how to further isolate the problem, I currently suspect a problem in `torch.ops.torch_sparse.non_diag_mask` [1, 2].

Versions:
```
  - python=3.8
  - pytorch=1.8.1
  - cudatoolkit=10.2
  - pip:
        - https://pytorch-geometric.com/whl/torch-1.8.0+cu102/torch_sparse-0.6.9-cp38-cp38-linux_x86_64.whl
        - torch-geometric==1.7.0
```

[1] https://github.com/rusty1s/pytorch_sparse/blob/master/csrc/diag.cpp
[2] https://github.com/rusty1s/pytorch_sparse/blob/master/csrc/cuda/diag_cuda.cu

**Comment by yascho** [comment]
My current workaround is to change `set_diag` to use CPU for the empty tensor case.
```
def set_diag(src: SparseTensor, values: Optional[Tensor] = None, k: int = 0) -> SparseTensor:
    src = remove_diag(src, k=k)
    row, col, value = src.coo()

    # mask = torch.ops.torch_sparse.non_diag_mask(row, col, src.size(0), src.size(1), k)
    if row.shape[0] == 0:
        mask = torch.ops.torch_sparse.non_diag_mask(row.cpu(), col.cpu(), src.size(0), src.size(1), k).cuda()
    else:
        mask = torch.ops.torch_sparse.non_diag_mask(row, col, src.size(0), src.size(1), k)

    inv_mask = ~mask 
```
Not optimal, as it does not fix the underlying issue in `non_diag_mask`, but works for me for now.

**Comment by rusty1s** [comment]
Thanks for reporting. The issue is that we are instantiating a kernel with zero threads, leading to this error. I fixed it in master, see [here](https://github.com/rusty1s/pytorch_sparse/commit/4c8e52983b5e0db7bd27173a928facc2b6924000).
