### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by quqxui** [rusty1s/pytorch_sparse#50]
```
  File "examples/sem_seg_sparse/train.py", line 142, in <module>
    main()
  File "examples/sem_seg_sparse/train.py", line 61, in main
    train(model, train_loader, optimizer, scheduler, criterion, opt)
  File "examples/sem_seg_sparse/train.py", line 79, in train
    out = model(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/deep_gcns_torch/examples/sem_seg_sparse/architecture.py", line 69, in forward
    feats.append(self.gunet(feats[-1],edge_index=edge_index ,batch=batch))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/models/graph_unet.py", line 83, in forward
    x.size(0))
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/models/graph_unet.py", line 120, in augment_adj
    num_nodes)
  File "/usr/local/lib/python3.6/dist-packages/torch_sparse/spspmm.py", line 30, in spspmm
    C = matmul(A, B)
  File "/usr/local/lib/python3.6/dist-packages/torch_sparse/matmul.py", line 107, in matmul
    return spspmm(src, other, reduce)
  File "/usr/local/lib/python3.6/dist-packages/torch_sparse/matmul.py", line 95, in spspmm
    return spspmm_sum(src, other)
  File "/usr/local/lib/python3.6/dist-packages/torch_sparse/matmul.py", line 83, in spspmm_sum
    rowptrA, colA, valueA, rowptrB, colB, valueB, K)
RuntimeError: CUDA error: an illegal memory access was encountered (launch_kernel at /pytorch/aten/src/ATen/native/cuda/Loops.cuh:103)
```

hi, i'm intergrating the **GraphU-Net** and other model on the google colab, but there are some bug , could you help me ?  thanks.

**Comment by rusty1s** [comment]
I will look into it.

**Comment by rusty1s** [comment]
Can you show me an example code? For example, my [GraphU-Net](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/graph_unet.py) script runs just fine. Note that you need to pass `coalesced=True` if your `edge_index` is not sorted.

**Comment by vthost** [comment]
I have the same problem it seems. @rusty1s Where exactly do I have to pass coalesced=True?

**Comment by rusty1s** [comment]
That was meant for the [`spspmm`](https://github.com/rusty1s/pytorch_sparse#sparse-sparse-matrix-multiplication) call inside the Graph-U-Net model, but it's actually not needed since [`augment_adj`](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/models/graph_unet.py#L116-L117) takes already care of that.

**Comment by vthost** [comment]
Yes. I get exactly the same error with GraphU-Net, and I have no idea why...

**Comment by rusty1s** [comment]
Can you do me a favor and run the `torch-sparse` test suite and see if that succeeds?

**Comment by vthost** [comment]
The tests run (apart from the ...metis) and, after running "python setup.py test" in the torch_sparse github project while having the anaconda environment where torch_sparse was already installed activated, the above error disappeared. So probably there was some build issue before? I though have a follow-up error, but that seems unrelated to this one.

**Comment by vthost** [comment]
Update: I now have the above error again :(

**Comment by rusty1s** [comment]
Mh, can you share the Google Collab with me? I want to take a closer look at it.

**Comment by rusty1s** [comment]
Do you have any insights on why it re-occurs?

**Comment by vthost** [comment]
No, I have no idea. But the code you posted runs without issues.

**Comment by vthost** [comment]
Ok, so the error now is actually not the same anymore (but seems related?). It's now in the pooling after augmenting the adjacency, but it seems that the latter is the problem.
```
Traceback (most recent call last):
  ...
  File ".../ogb_examples/graphproppred/code/gnn2.py", line 528, in compute_message_layers
    return self.unet(feat, edge_index, batch)
  File "/opt/anaconda3/envs/dagnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/envs/dagnn/lib/python3.7/site-packages/torch_geometric/nn/models/graph_unet.py", line 86, in forward
    x, edge_index, edge_weight, batch)
  File "/opt/anaconda3/envs/dagnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/envs/dagnn/lib/python3.7/site-packages/torch_geometric/nn/pool/topk_pool.py", line 158, in forward
    num_nodes=score.size(0))
  File "/opt/anaconda3/envs/dagnn/lib/python3.7/site-packages/torch_geometric/nn/pool/topk_pool.py", line 60, in filter_adj
    row, col = row[mask], col[mask]
RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered
```
Looking into the shapes in graph_unet as 
``` 
 for i in range(1, self.depth + 1):  
            print("*"*50,i,x.shape,edge_index.shape,max(edge_index[0]),max(edge_index[1]))
            edge_index, edge_weight = self.augment_adj(edge_index, edge_weight,
                                                       x.size(0))
            print("*"*50,i,x.shape,edge_index.shape,max(edge_index[0]),max(edge_index[1]))
            x, edge_index, edge_weight, batch, perm, _ = self.pools[i - 1](
                x, edge_index, edge_weight, batch)
```
I get
````
************************************************** 1 5 torch.Size([22225, 300]) torch.Size([2, 61178]) tensor(22224, device='cuda:0') tensor(22224, device='cuda:0')
************************************************** 1 5 torch.Size([22225, 300]) torch.Size([2, 197014]) tensor(22224, device='cuda:0') tensor(493906172, device='cuda:0')
````
Then the numbers in edge_index are too large in filter_adj in topk_pool l58 (in the message it's l60 because I added prints). I hope that helps. I think I cannot resolve it alone since I am not fully sure about the meaning/internals of spmm in augment_adj.

**Comment by rusty1s** [comment]
Yeah, it looks like the `spspmm` call does not work for you since it does not compute `edge_index[1]` correctly. It's `max` value should also not exceed `22224`. Not sure how to fix it though :(

**Comment by vthost** [comment]
You mention above that `coalesced` is relevant for sorting. I am using `ogbg-code`. The example code for that data adds two types of edges to the graph in `utils.augment_edge`, so we might have several edges between two nodes. I tried to add `coalesced=True` in `graph_unet.augment_edge` as argument to `spspmm` but the error is still the same. It seems that `spspmm` interprets the `coalesced` argument as "sorted". After I added the following in the beginning of `graph_unet.unet.forward` (after the initialization of the edge weights) it finally runs!
```edge_index, edge_weight = coalesce(edge_index, edge_weight, x.shape[0], x.shape[0])```
Just one side question, what does `spspmm` actually achieve? It multiplies the edge indices, but all values are 0 or 1 no?

**Comment by vthost** [comment]
I now have this also with ASAPool :(
<img width="959" alt="Screen Shot 2020-08-16 at 5 40 36 PM" src="https://user-images.githubusercontent.com/20739063/90344634-83cf5b00-dfe9-11ea-927f-142b967384cb.png">

**Comment by Flawless1202** [comment]
@vthost @rusty1s Hi, I also met this error when use my own dataset to train `Graph-UNet`. This error randomly occurred when using GPU but never occurred when using CPU. I changed the `augment_adj` function, added the `remove_self_loops` function at first, and then the problem was solved. But I don't know why.
```python
def augment_adj(self, edge_index, edge_weight, num_nodes):
    edge_index, edge_weight = remove_self_loops(edge_index, edge_weight)
    edge_index, edge_weight = add_self_loops(edge_index, edge_weight, num_nodes=num_nodes)
    edge_index, edge_weight = sort_edge_index(edge_index, edge_weight, num_nodes)
    edge_index, edge_weight = spspmm(edge_index, edge_weight, edge_index, edge_weight, num_nodes, num_nodes, num_nodes)
    edge_index, edge_weight = remove_self_loops(edge_index, edge_weight)
    return edge_index, edge_weight
```

**Comment by rusty1s** [comment]
The error seems to stem from the fact cuSPARSE cannot handle duplicated edges in `edge_index`. The reason for that is that it fails to compute the correct amount of output edges this way. In your case, it might well be that you have some initial self-loop edges in your graph, which should be removed before calling `add_self_loops`. I think your fix for `augment_adj` is correct, and I added it to the `GraphUNet` model in PyG.

**Comment by Flawless1202** [comment]
OK, @rusty1s  Thx a lot!

**Comment by vthost** [comment]
I have duplicate edges but no self loops. For ASAPool calling `coerce` in the beginning of forward seems to work regarding the above error. But then I receive a CUDA out of memory after a few epochs. Since the latter occurs even with batch size 2, I am not sure if that's due to the model or connected to the above?

**Comment by rusty1s** [comment]
I don't think that's related to the above issue. You may have a memory leak somewhere, or one of your graphs in your dataset is too large that it can not be handled in a full-batch fashion.

**Comment by andreimargeloiu** [comment]
similar to @vthost , I had this issue (with `spspmm_sum`) when using the ASAPool layer. 

The solution was to do `edge_index = tg.utils.coalesce(edge_index, is_sorted=False)` before passing edge_index through the ASAPool layer
